export default [
  {
    id: 0,
    musica: "./music/MJ_Billie_Jean.mp3",
    nome_musica: "Billie Jean",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/BillieJean.jpg",
  },
  {
    id: 1,
    musica: "./music/MJ_Smooth_Criminal.mp3",
    nome_musica: "Smooth Criminal",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/Smooth_Criminal.jpg",
  },
  {
    id: 2,
    musica: "./music/MJ_Thriller.mp3",
    nome_musica: "Thriller",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/BillieJean.jpg",
  },
  {
    id: 3,
    musica: "./music/MJ_Remember_The_Time.mp3",
    nome_musica: "Remember the Time",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/Remember_the_Time.jpg",
  },
  {
    id: 4,
    musica: "./music/MJ_Bad.m4a",
    nome_musica: "Bad",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/Bad.jpg",
  },
  {
    id: 5,
    musica: "./music/MJ_Black_Or_White.mp3",
    nome_musica: "Black Or White",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/BlackOrWhite.jpg",
  },
  {
    id: 6,
    musica: "./music/MJ_A_Place_With_No_Name.m4a",
    nome_musica: "Place With no Name",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/A_Place_With_No_Name.jpg",
  },
  {
    id: 7,
    musica: "./music/MJ_Dont_Stop_Til_You_Get_Enough.mp3",
    nome_musica: "Don't Stop Til You Get Enought",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/DontStopTil.jpg",
  },
  {
    id: 8,
    musica: "./music/MJ_Earth_Song.mp3",
    nome_musica: "Earth Song",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/EarthSong.jpg",
  },
  {
    id: 9,
    musica: "./music/MJ_They_Dont_Care_About_Us.m4a",
    nome_musica: "They Don't Care About Us",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/They_Dont_Care_About_Us.jpg",
  },
  {
    id: 10,
    musica: "./music/MJ_Man_in_the_Mirror.mp3",
    nome_musica: "Man in The Mirror",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/Man_in_the_Mirror.jpg",
  },
  {
    id: 11,
    musica: "./music/MJ_Human_Nature.mp3",
    nome_musica: "Humam Nature",
    nome_artista: "Michael Jackson",
    imagem_musica: "./image/HumanNature.jpg",
  },
];
